create table if not exists businesses (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  type text not null check (type in ('salon', 'restaurant')),
  whatsapp_phone_number_id text not null unique,
  business_data jsonb not null default '{}'::jsonb,
  system_prompt_extra text,
  created_at timestamptz not null default now()
);

create table if not exists conversations (
  id bigint generated by default as identity primary key,
  business_id uuid not null references businesses(id) on delete cascade,
  customer_phone text not null,
  message_direction text not null check (message_direction in ('in', 'out')),
  message_text text not null,
  created_at timestamptz not null default now()
);

create index if not exists conversations_lookup_idx
  on conversations (business_id, customer_phone, created_at desc);

create table if not exists leads (
  id bigint generated by default as identity primary key,
  business_id uuid not null references businesses(id) on delete cascade,
  customer_phone text not null,
  customer_name text,
  requested_service text,
  requested_datetime text,
  order_items jsonb,
  delivery_address text,
  contact_number text,
  status text not null default 'new' check (status in ('new', 'contacted', 'booked')),
  created_at timestamptz not null default now()
);

create index if not exists leads_lookup_idx
  on leads (business_id, status, created_at desc);

alter table leads add column if not exists order_items jsonb;
alter table leads add column if not exists delivery_address text;
alter table leads add column if not exists contact_number text;
